from enum import IntEnum


class LoginCommandCode(IntEnum):
    WELCOME_NOTIFY = 16
    LOGIN_REQ = 17
    LOGIN_ANSWER = 18
    LOGOUT_REQ = 19
    LOGOUT_ANSWER = 20
    SERVER_LIST_REQ = 23
    SERVER_LIST_ANSWER = 24
    REGISTER_REQ = 33
    REGISTER_ANSWER = 34


class WorldCommandCode(IntEnum):
    WORLD_LOGIN_REQ = 33
    WORLD_LOGIN_ANSWER = 34
    WORLD_PING_ECHO = 49
    WORLD_CLIENT_SAVE_CONFIG_NOTIFY = 50
    PVE_MAPS_REQ = 81
    PVE_MAPS_ANSWER = 82


class RoleCommandCode(IntEnum):
    ROLE_LIST_REQ = 257
    ROLE_LIST_ANSWER = 258
    ROLE_NAME_CONFIRM_REQ = 259
    ROLE_NAME_CONFIRM_ANSWER = 260
    CREATE_ROLE_REQ = 261
    CREATE_ROLE_ANSWER = 262
    DELETE_ROLE_REQ = 263
    DELETE_ROLE_ANSWER = 264
    SELECT_ROLE_REQ = 265
    SELECT_ROLE_ANSWER = 272
    RECOVER_ROLE_REQ = 273
    RECOVER_ROLE_ANSWER = 274
    SET_ROLE_PW_REQ = 275
    SET_ROLE_PW_ANSWER = 276


class PlayerCommandCode(IntEnum):
    PLAYER_ENTER_WORLD_REQ = 513
    PLAYER_ENTER_WORLD_ANSWER = 514
    PLAYER_LEAVE_WORLD_REQ = 515
    PLAYER_LEAVE_WORLD_ANSWER = 516
    PLAYER_ENTER_MAP_REQ = 517
    PLAYER_ENTER_MAP_ANSWER = 518
    PLAYER_MOVE_REQ = 519
    PLAYER_POSITION_CHECK_NOTIFY = 520
    PLAYER_VIEW_MAP_REQ = 521
    PLAYER_VIEW_MAP_ANSWER = 522
    PLAYER_SELECT_LINE_REQ = 523
    PLAYER_USE_SKILL_REQ = 545
    PLAYER_LUCKY_SKILL_NOTIFY = 547
    PLAYER_CANCEL_SKILL_REQ = 548
    PLAYER_SKILL_INTERRUPTED_NOTIFY = 549
    PLAYER_HP_CHANGE_NOTIFY = 550
    PLAYER_HPMAX_CHANGE_NOTIFY = 551
    PLAYER_MP_CHANGE_NOTIFY = 552
    PLAYER_MPMAX_CHANGE_NOTIFY = 553
    PLAYER_BUFF_CHANGE_NOTIFY = 560
    PLAYER_EXP_CHANGE_NOTIFY = 561
    PLAYER_LEVEL_UP_NOTIFY = 562
    PLAYER_GOLD_CHANGE_NOTIFY = 563
    PLAYER_MONEY_CHANGE_NOTIFY = 564
    PLAYER_DIED_NOTIFY = 565
    PLAYER_SEND_MSG_REQUEST = 673
    PLAYER_RECEIVE_MSG_NOTIFY = 674
    PLAYER_RECEIVE_SYS_PROMPT_NOTIFY = 675
    PLAYER_SHOW_TALKS_NOTIFY = 676


class BagCommandCode(IntEnum):
    PLAYER_BAG_CHECK_NOTIFY = 5121
    PLAYER_BAG_CAPACITY_CHANGE_NOTIFY = 5122
    PLAYER_PICKUP_ITEM_REQ = 5123
    PLAYER_PICKUP_ITEM_ANSWER = 5124
    PLAYER_USE_ITEM_REQ = 5124
    PLAYER_ITEM_USED_NOTIFY = 5130
    PLAYER_MOVE_ITEM_REQ = 5125
    PLAYER_SPLIT_ITEM_REQ = 5126
    PLAYER_DROP_ITEM_REQ = 5127
    PLAYER_MOVE_ITEM_CROSS_BAG_REQ = 5128
    PLAYER_VIEW_BAG_REQ = 5129
    PLAYER_ITEM_ADDED_NOTIFY = 5131
    PLAYER_ITEM_CD_CHECK_NOTIFY = 5132
    PLAYER_VIEW_ITEM_REQ = 5133
    PLAYER_VIEW_ITEM_ANSWER = 5134
    PLAYER_RENEW_ITEM_REQ = 5137
    PLAYER_BUY_AND_USE_ITEM_REQ = 5138
    PLAYER_BAG_SORT_REQ = 5141


class EquipmentCommandCode(IntEnum):
    PLAYER_REMOVE_EQUIPMENT_REQ = 4610
    PLAYER_EQUIPMENT_CHECK_NOTIFY = 4609


class ShopCommandCode(IntEnum):
    SHOP_SELL_ITEM_REQ = 2817
    SHOP_BUY_ITEM_REQ = 2818
    STORE_BUY_ITEM_REQ = 2819
    LEAD_ITEM_INFO_NOTIFY = 2820
    LEAD_ITEM_INFO_REQ = 2821
    LEAD_BUY_ITEM_REQ = 2822
    VIP_SHOP_BUY_ITEM_REQ = 2823
    VIP_SHOP_BUY_ITEM_ANSWER = 2824
    SHOP_SELL_ITEM_ANSWER = 2825
    SHOP_BUY_ITEM_ANSWER = 2826
    REWARD_SHOP_BUY_REQ = 10557
    REWARD_SHOP_BUY_ANSWER = 10558
    VAR_SHOP_BUY_REQ = 10560
    VAR_SHOP_BUY_ANSWER = 10561
